name: Release 🚀

on:
  pull_request:
    branches: master
  push:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ['12', '14']
    name: Node ${{ matrix.node }} build
    steps:
      - uses: actions/checkout@v2 
      - name: 👀 Cache node_modules 
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{runner.os}}-node-${{ hashFiles('**/pnpm-lock.yaml')}}
          restore-keys: |
            ${{ runner.os }}-node
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.node}}
      - uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.6
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]
      - run: pnpm run test:cov
      - name: Upload Test Coverage
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage
          path: coverage.zip
      - name: ZIP Coverage
        if: github.event_name == 'push'
        run: zip -r coverage.zip ./coverage
      - name: Upload build
        if: github.event_name == 'push'
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: build
      - name: ZIP Build Assets
        if: github.event_name == 'push'
        run: zip -r build.zip ./dist
  release:
    if: github.event_name == 'push'
    needs: build_and_test
    name: Release Package 🏎️
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: 👀 Cache node_modules
        uses: actions/cache@v1
        with:
          path: ~/.pnpm-store
          key: ${{runner.os}}-node-${{ hashFiles('**/pnpm-lock.yaml')}}
          restore-keys: |
            ${{ runner.os }}-node
      - name: 🏗️ Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: 🤹‍♂️ Setup PNPM
        uses: pnpm/action-setup@v1.2.1
        with:
          version: 5.13.6
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]