name: Notify on Issue
on:
  issues:
    types: [opened]

jobs:
  slack-message:
    runs-on: ubuntu-latest
    steps:
      - name: ✉️  Message to Discord
        uses: tsickert/discord-webhook@v0.0.7
        with:
          webhook-url: ${{secrets.DISCORD_WEBHOOK}}
          content: "New issue was created: [${{github.event.issue.title}}](${{github.event.issue.html_url}})"